M48
; DRILL file {KiCad (6.0.4-0)} date Wednesday, January 11, 2023 at 12:36:20 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-11T12:36:20-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X7.6552Y-3.7309
X7.6572Y-3.5033
T2
X5.5709Y-3.8268
X5.8425Y-3.8268
T0
M30
