M48
; DRILL file {KiCad (7.0.0-0)} date Sunday, May 07, 2023 at 02:23:39 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-07T02:23:39-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
%
G90
G05
T1
X7.6552Y-3.7309
X7.6572Y-3.5033
T2
X5.5709Y-3.8268
X5.8425Y-3.8268
T0
M30
