M48
; DRILL file {KiCad (7.0.0-0)} date Monday, September 11, 2023 at 01:39:21 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-11T01:39:21-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0512
%
G90
G05
T1
X7.6552Y-3.7309
X7.6572Y-3.5033
T2
X5.4862Y-3.8563
T3
X4.3784Y-4.1398
X4.3784Y-4.3366
T0
M30
